### ISSUE TITLE
Create new tag on version bump

### ISSUE THREAD

**Issue by edance** [cooperka/bash-git-utils#2]

**Comment by cooperka** [comment]
You can use [`push_tag`](https://github.com/cooperka/git-utils/blob/master/git_utils#L69) in your custom script, but this should be done by default! This whole codebase is a bit confusing to me looking back at it... it definitely needs a refactor.

**Comment by cooperka** [comment]
Turns out this is already explained in the [readme](https://github.com/cooperka/git-utils#example) 😜 

Run `cut_release 1.0` and it will tag along with the version bump.
